### PR TITLE
adding dark mode feature

### PR DESCRIPTION
**Pull request by lertazen**
I have added the dark mode feature based on the dark mode image on the top right of the page. The colors of some of the elements may not suit your expectations. Please let me know if there is any changes I need to make.

### CODE REVIEW

**Review by arpittyagi102 — COMMENTED** [review]
hello @lertazen, your code is giving this error on console
```bash
ReferenceError: systemTheme is not defined
    at a (index-5d7a9ed011f23cbe.js:1:488)
    at ab (framework-6cbe6e332df95288.js:9:60909)
    at i (framework-6cbe6e332df95288.js:9:119453)
    at oF (framework-6cbe6e332df95288.js:9:99102)
    at framework-6cbe6e332df95288.js:9:98969
    at oO (framework-6cbe6e332df95288.js:9:98976)
    at ox (framework-6cbe6e332df95288.js:9:95728)
    at oS (framework-6cbe6e332df95288.js:9:94283)
    at x (framework-6cbe6e332df95288.js:33:1364)
    at MessagePort.T (framework-6cbe6e332df95288.js:33:1894)
```
Kindly look into it

**Comment by lertazen** [comment]
Hi, @arpittyagi102 
I removed the use of systemTheme. Let me know if the error still persists. Thanks

**Review by arpittyagi102 — APPROVED** [review]
Hey @lertazen, please change the light green color to dark green color in the dark mode

**Review by arpittyagi102 — APPROVED** [review]
Hello @lertazen,
Thank you so much for your contribution, I am merging this pull request

**Comment by lertazen** [comment]
Hi @arpittyagi102 ,

Thank you for reviewing and merging my pull request! I'm glad I could contribute to your project. 

Best regards

**Pull request merged**
